[build]
  builder = "DOCKER"
  dockerfilePath = "backend/Dockerfile"
  dockerContext = "backend/"

[deploy]
  healthcheckPath = "/health"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
